#!/bin/bash
BLUE=$1
GREEN=$2

sed -i "s/$BLUE/blue_temp/g" /etc/nginx/conf.d/default.conf
sed -i "s/$GREEN/green_temp/g"  /etc/nginx/conf.d/default.conf
sed -i "s/blue_temp/$GREEN/g"  /etc/nginx/conf.d/default.conf
sed -i "s/green_temp/$BLUE/g"  /etc/nginx/conf.d/default.conf

/etc/init.d/nginx reload