#!/bin/bash

sed -i 's/blue/blue_temp/g' /etc/nginx/conf.d/default.conf
sed -i 's/green/green_temp/g'  /etc/nginx/conf.d/default.conf
sed -i 's/blue_temp/green/g'  /etc/nginx/conf.d/default.conf
sed -i 's/green_temp/blue/g'  /etc/nginx/conf.d/default.conf

/etc/init.d/nginx reload