#!/bin/bash

sed -i 's/${blueset}/blue_temp/g' /etc/nginx/conf.d/default.conf
sed -i 's/${greenset}/green_temp/g'  /etc/nginx/conf.d/default.conf
sed -i 's/blue_temp/${greenset}/g'  /etc/nginx/conf.d/default.conf
sed -i 's/green_temp/${blueset}/g'  /etc/nginx/conf.d/default.conf

/etc/init.d/nginx reload